name: CI Debug

on:
  workflow_dispatch: # 手動実行用ボタンを追加
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Register SSH Public Key from Secret
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          name: My Artifact
          files: |
            /home/runner/my-artifact/*
